{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TupleSections     #-}

module Text.XML.Decode
  ( DecodeCursor
  , CursorHistory
  , DecodeResult
  , Predicate(..)
  , Shift
  , ChoiceDecoder
  , decode
  , decodeDocument
  , decodeSingle
  , decodeDefault
  , decodeMay
  , decodeMany
  , decodeNel
  , decodeAttr
  , decodeAttrMay
  , decodeChoice
  , choice
  , foldCursor
  , HCursor
  , CursorOp(..)
  , CursorAxis(..)
  , fromCursor
  , fromDocument
  , failedCursor
  , successfulCursor
  -- Parser Helpers
  , parseCursor
  , parseMaybe
  , parseText
  , parseInt
  , parseInteger
  , parseDouble
  , parseBool
  , parseIsoUtcTime
  , parseIsoDay
  , parseXmlTime
  -- HCursor Lenses / Prisms
  , cursors
  , history
  , _Child
  , _Descendant
  , _ChoiceSucceed
  , _ChoiceSwitch
  , _GenericOp
  , _MoveAxis
  , _LaxElement
  , _FailedCompose
  -- Shifts
  , laxElement
  , shiftGeneric
  , filterPred
  , (|||)
  , (***)
  , (%/)
  , (%//)
  , ($/)
  , ($//)
  , (&/)
  , (&//)
  -- Dates
  , IsoUTCTime(..)
  , IsoDay(..)
  , isoUTCTimeFormat
  , isoDayFormat
  ) where

import           Text.XML.Decode.DecodeCursor
import           Text.XML.Decode.HCursor
import           Text.XML.Decode.Parsers
import           Text.XML.Decode.Time
